---
title: "COP21 Datapack App Analytics"
output:
  pdf_document: default
html_document:
  df_print: paged
lang: "en-US"
date: '`r format(Sys.time(), "%d %B, %Y %H:%M")`'
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(data.table)
require(magrittr)
require(purrr)
require(dplyr)
require(tidyr)
require(knitr)
require(ggplot2)
require(paws)
require(connectapi)
require(lubridate)
require(noctua)

#Connect to the Athena database
con <- dbConnect(noctua::athena())


Sys.setlocale("LC_MESSAGES", 'en_GB.UTF-8')
Sys.setenv(LANG = "en_US.UTF-8")

```


## Summary info
```{r summary_info, eval=TRUE, echo=FALSE}

d_events <- dbGetQuery(con,"SELECT event_type,tool,datapack_name,cop_year,
CAST(date_parse(ts, '%Y-%m-%dT%T+0000') as date) as event_date ,uuid,user
FROM datapack.cop22_app_events WHERE cop_year = 2022;")

events_type_map <- tibble::tribble(
  ~event_type, ~message,
  "VALIDATE","Validation",
  "COMPARISON_DOWNLOAD","Comparison",
  "MESSAGE_DOWNLOAD","Messages",
  "FLATPACK_DOWNLOAD", "Flatpack",
  "VR_RULES_DOWNLOAD","Validation rules",
  "DATAPACK_DOWNLOAD","Datapack",
  "CSO_FLATPACK_DOWNLOAD","CSO Flatpack",
  "MEMO_DOWNLOAD","COP Memo"
)

start_date<-min(d_events$event_date)
end_date<-max(d_events$event_date)

d_events <- d_events %>%  dplyr::left_join(events_type_map)

validations <- d_events %>%  dplyr::filter(event_type == "VALIDATE") 

downloads <- d_events %>% dplyr::filter(stringr::str_detect(event_type,"DOWNLOAD"))

```


- Total validations: `r NROW(validations)`
- Total downloasds: `r NROW(downloads)`
- Unique users: `r unique(d_events$user)`
- First validation on: `r start_date`
- Last validation on: `r end_date`

## Validations by country

```{r validations_by_country, eval=TRUE, echo=FALSE}
validations_by_country_total<-
validations %>% 
  dplyr::select(Country=datapack_name,event_date) %>% 
  dplyr::group_by(Country) %>% 
  dplyr::summarise(Validations=n()) %>% 
  dplyr::arrange(-Validations)

kable(validations_by_country_total)
```

## Validations by day

```{r validations_by_date, eval=TRUE, echo=FALSE}

#Validations by date
validations_by_date_total<-
validations %>% 
  dplyr::select(Date=event_date) %>% 
  dplyr::group_by(Date) %>% 
  dplyr::summarise(Validations = dplyr::n())

ggplot(validations_by_date_total,aes(x = Date, y= Validations)) + geom_col()


```


## Downloads by day and type

```{r validations_by_date, eval=TRUE, echo=FALSE}

#Validations by date
downloads_by_day_type<-
downloads %>% 
  dplyr::select(Date=event_date,Type = message,event_type) %>% 
  dplyr::group_by(Date,Type,event_type) %>% 
  dplyr::summarise(Downloads = dplyr::n())

ggplot(validations_by_date_total,aes(x = Date, y= Validations)) + geom_col()  + facet_grid(. ~ supp)


```




<!-- ## Validation issues -->
<!-- ```{r issue_summary, eval=FALSE, echo=FALSE} -->
<!-- #Issue summary -->

<!-- issue_summary<-d_validation_details%>%  -->
<!--   dplyr::select(country_name,event_date,validation_issue_category) %>%  -->
<!--   dplyr::group_by(validation_issue_category) %>%  -->
<!--   dplyr::summarise(count=dplyr::n()) %>%  -->
<!--   dplyr::arrange(-count) %>%  -->
<!--   dplyr::mutate(occurrence_rate = ( (100*count/total_validations) %>% round(.,digits = 1)  ) ) %>%  -->
<!--   dplyr::select(-count) %>%  -->
<!--   dplyr::rename(Category = validation_issue_category, -->
<!--                 "Occurrence (%)" = occurrence_rate) -->


<!-- kable(issue_summary) -->
<!-- ```  -->

<!-- ```{r shiny_load_data, eval=FALSE, echo=FALSE} -->


<!-- days_back <- as.numeric(Sys.getenv("DAYSBACK", 365)) -->

<!-- default_content_title <- "Unknown (Deleted Content?)" -->

<!-- report_from <- lubridate::today() - lubridate::ddays(days_back) -->

<!-- client <- connectapi::connect() -->
<!-- shiny <- get_usage_shiny( -->
<!--   client, -->
<!--   from = report_from, -->
<!--   limit = Inf -->
<!-- ) %>% -->
<!--   mutate( -->
<!--     started = lubridate::ymd_hms(started), -->
<!--     ended = lubridate::ymd_hms(ended), -->
<!--     session_duration = ended - started -->
<!--     ) %>% -->
<!--   filter(session_duration > lubridate::dseconds(5)) -->

<!-- content <- get_usage_static( -->
<!--   client, -->
<!--   from = report_from, -->
<!--   limit = Inf -->
<!-- ) -->

<!-- all_users <- get_users(client, page_size = 500) -->

<!-- data <-   list(shiny = shiny, content = content) -->
<!-- ``` -->


<!-- ## Connect server stats -->
<!-- ```{r shiny_over_time, eval=TRUE, echo=FALSE} -->
<!-- data$shiny %>% -->
<!--     mutate(day = round_date(started, "day")) %>%  -->
<!--     group_by(day) %>%  -->
<!--     filter(day > today() - ddays(days_back)) %>%  -->
<!--     summarise(visits = n()) %>%  -->
<!--     arrange(desc(visits)) %>%  -->
<!--     {ggplot(., aes(day, visits)) +  -->
<!--             geom_bar(stat = "identity") +  -->
<!--             labs( -->
<!--                 y = "# of Shiny Sessions", -->
<!--                 x = NULL -->
<!--             )} -->
<!-- ``` -->


<!-- ## Datapack sessions by day -->
<!-- ```{r datapack_over_time, eval=FALSE, echo=FALSE} -->
<!-- data$shiny %>%  -->
<!--       mutate(time = ymd_hms(started), -->
<!--           day = round_date(started, "day")) %>%  -->
<!--   dplyr::select(content_guid,time,day) %>%  -->
<!--   group_by(content_guid,day) %>%  -->
<!--   summarize(visits = n()) %>%  -->
<!--   arrange(content_guid,desc(visits)) %>%  -->
<!--   mutate(name = purrr::map_chr(content_guid, ~ content_title(client, .x, default_content_title))) %>%  -->
<!--   dplyr::filter(name == Sys.getenv("APP_NAME")) %>%  -->
<!--   {  ggplot(., aes(day, visits)) +  -->
<!--      geom_bar(stat = "identity") +   -->
<!--      labs( -->
<!--        y = "# of Datapack sessions by day", -->
<!--        x = "Date" -->
<!--      )}  -->
<!-- ``` -->